service: rock-paper-scissors-service

provider:
  name: aws
  runtime: nodejs6.10
  region: ${env:REGION}
  stage: ${env:STAGE}

functions:
  pickShape:
    handler: serverless/handlers.play
    events:
      - http:
          path: play
          method: get
          cors:
            origin: '*'
            maxAge: 86400